{
    "success":true,
    "isException":false,
    "area":null,
    "city":null,
    "cityId":null,
    "exception":false,
    "jiageCities":null,
    "proId":null,
    "successResultValue":null,
    "cities":[
        {
            "name":"市辖区",
            "id":"110100",
            "cityPinyin":"市辖区",
            "lastModifyTime":null,
            "provinceId":"110000",
            "hotCity":false,
            "cityShortPY":"市辖区"
        },
        {
            "name":"县",
            "id":"110200",
            "cityPinyin":"县",
            "lastModifyTime":null,
            "provinceId":"110000",
            "hotCity":false,
            "cityShortPY":"县"
        },
        {
            "name":"市辖区",
            "id":"120100",
            "cityPinyin":"市辖区",
            "lastModifyTime":null,
            "provinceId":"120000",
            "hotCity":false,
            "cityShortPY":"市辖区"
        },
        {
            "name":"县",
            "id":"120200",
            "cityPinyin":"县",
            "lastModifyTime":null,
            "provinceId":"120000",
            "hotCity":false,
            "cityShortPY":"县"
        },
        {
            "name":"石家庄市",
            "id":"130100",
            "cityPinyin":"石家庄市",
            "lastModifyTime":null,
            "provinceId":"130000",
            "hotCity":false,
            "cityShortPY":"石家庄市"
        },
        {
            "name":"唐山市",
            "id":"130200",
            "cityPinyin":"唐山市",
            "lastModifyTime":null,
            "provinceId":"130000",
            "hotCity":false,
            "cityShortPY":"唐山市"
        },
        {
            "name":"秦皇岛市",
            "id":"130300",
            "cityPinyin":"秦皇岛市",
            "lastModifyTime":null,
            "provinceId":"130000",
            "hotCity":false,
            "cityShortPY":"秦皇岛市"
        },
        {
            "name":"邯郸市",
            "id":"130400",
            "cityPinyin":"邯郸市",
            "lastModifyTime":null,
            "provinceId":"130000",
            "hotCity":false,
            "cityShortPY":"邯郸市"
        },
        {
            "name":"邢台市",
            "id":"130500",
            "cityPinyin":"邢台市",
            "lastModifyTime":null,
            "provinceId":"130000",
            "hotCity":false,
            "cityShortPY":"邢台市"
        },
        {
            "name":"保定市",
            "id":"130600",
            "cityPinyin":"保定市",
            "lastModifyTime":null,
            "provinceId":"130000",
            "hotCity":false,
            "cityShortPY":"保定市"
        },
        {
            "name":"张家口市",
            "id":"130700",
            "cityPinyin":"张家口市",
            "lastModifyTime":null,
            "provinceId":"130000",
            "hotCity":false,
            "cityShortPY":"张家口市"
        },
        {
            "name":"承德市",
            "id":"130800",
            "cityPinyin":"承德市",
            "lastModifyTime":null,
            "provinceId":"130000",
            "hotCity":false,
            "cityShortPY":"承德市"
        },
        {
            "name":"沧州市",
            "id":"130900",
            "cityPinyin":"沧州市",
            "lastModifyTime":null,
            "provinceId":"130000",
            "hotCity":false,
            "cityShortPY":"沧州市"
        },
        {
            "name":"廊坊市",
            "id":"131000",
            "cityPinyin":"廊坊市",
            "lastModifyTime":null,
            "provinceId":"130000",
            "hotCity":false,
            "cityShortPY":"廊坊市"
        },
        {
            "name":"衡水市",
            "id":"131100",
            "cityPinyin":"衡水市",
            "lastModifyTime":null,
            "provinceId":"130000",
            "hotCity":false,
            "cityShortPY":"衡水市"
        },
        {
            "name":"太原市",
            "id":"140100",
            "cityPinyin":"太原市",
            "lastModifyTime":null,
            "provinceId":"140000",
            "hotCity":false,
            "cityShortPY":"太原市"
        },
        {
            "name":"大同市",
            "id":"140200",
            "cityPinyin":"大同市",
            "lastModifyTime":null,
            "provinceId":"140000",
            "hotCity":false,
            "cityShortPY":"大同市"
        },
        {
            "name":"阳泉市",
            "id":"140300",
            "cityPinyin":"阳泉市",
            "lastModifyTime":null,
            "provinceId":"140000",
            "hotCity":false,
            "cityShortPY":"阳泉市"
        },
        {
            "name":"长治市",
            "id":"140400",
            "cityPinyin":"长治市",
            "lastModifyTime":null,
            "provinceId":"140000",
            "hotCity":false,
            "cityShortPY":"长治市"
        },
        {
            "name":"晋城市",
            "id":"140500",
            "cityPinyin":"晋城市",
            "lastModifyTime":null,
            "provinceId":"140000",
            "hotCity":false,
            "cityShortPY":"晋城市"
        },
        {
            "name":"朔州市",
            "id":"140600",
            "cityPinyin":"朔州市",
            "lastModifyTime":null,
            "provinceId":"140000",
            "hotCity":false,
            "cityShortPY":"朔州市"
        },
        {
            "name":"晋中市",
            "id":"140700",
            "cityPinyin":"晋中市",
            "lastModifyTime":null,
            "provinceId":"140000",
            "hotCity":false,
            "cityShortPY":"晋中市"
        },
        {
            "name":"运城市",
            "id":"140800",
            "cityPinyin":"运城市",
            "lastModifyTime":null,
            "provinceId":"140000",
            "hotCity":false,
            "cityShortPY":"运城市"
        },
        {
            "name":"忻州市",
            "id":"140900",
            "cityPinyin":"忻州市",
            "lastModifyTime":null,
            "provinceId":"140000",
            "hotCity":false,
            "cityShortPY":"忻州市"
        },
        {
            "name":"临汾市",
            "id":"141000",
            "cityPinyin":"临汾市",
            "lastModifyTime":null,
            "provinceId":"140000",
            "hotCity":false,
            "cityShortPY":"临汾市"
        },
        {
            "name":"吕梁市",
            "id":"141100",
            "cityPinyin":"吕梁市",
            "lastModifyTime":null,
            "provinceId":"140000",
            "hotCity":false,
            "cityShortPY":"吕梁市"
        },
        {
            "name":"呼和浩特市",
            "id":"150100",
            "cityPinyin":"呼和浩特市",
            "lastModifyTime":null,
            "provinceId":"150000",
            "hotCity":false,
            "cityShortPY":"呼和浩特市"
        },
        {
            "name":"包头市",
            "id":"150200",
            "cityPinyin":"包头市",
            "lastModifyTime":null,
            "provinceId":"150000",
            "hotCity":false,
            "cityShortPY":"包头市"
        },
        {
            "name":"乌海市",
            "id":"150300",
            "cityPinyin":"乌海市",
            "lastModifyTime":null,
            "provinceId":"150000",
            "hotCity":false,
            "cityShortPY":"乌海市"
        },
        {
            "name":"赤峰市",
            "id":"150400",
            "cityPinyin":"赤峰市",
            "lastModifyTime":null,
            "provinceId":"150000",
            "hotCity":false,
            "cityShortPY":"赤峰市"
        },
        {
            "name":"通辽市",
            "id":"150500",
            "cityPinyin":"通辽市",
            "lastModifyTime":null,
            "provinceId":"150000",
            "hotCity":false,
            "cityShortPY":"通辽市"
        },
        {
            "name":"鄂尔多斯市",
            "id":"150600",
            "cityPinyin":"鄂尔多斯市",
            "lastModifyTime":null,
            "provinceId":"150000",
            "hotCity":false,
            "cityShortPY":"鄂尔多斯市"
        },
        {
            "name":"呼伦贝尔市",
            "id":"150700",
            "cityPinyin":"呼伦贝尔市",
            "lastModifyTime":null,
            "provinceId":"150000",
            "hotCity":false,
            "cityShortPY":"呼伦贝尔市"
        },
        {
            "name":"巴彦淖尔市",
            "id":"150800",
            "cityPinyin":"巴彦淖尔市",
            "lastModifyTime":null,
            "provinceId":"150000",
            "hotCity":false,
            "cityShortPY":"巴彦淖尔市"
        },
        {
            "name":"乌兰察布市",
            "id":"150900",
            "cityPinyin":"乌兰察布市",
            "lastModifyTime":null,
            "provinceId":"150000",
            "hotCity":false,
            "cityShortPY":"乌兰察布市"
        },
        {
            "name":"兴安盟",
            "id":"152200",
            "cityPinyin":"兴安盟",
            "lastModifyTime":null,
            "provinceId":"150000",
            "hotCity":false,
            "cityShortPY":"兴安盟"
        },
        {
            "name":"锡林郭勒盟",
            "id":"152500",
            "cityPinyin":"锡林郭勒盟",
            "lastModifyTime":null,
            "provinceId":"150000",
            "hotCity":false,
            "cityShortPY":"锡林郭勒盟"
        },
        {
            "name":"阿拉善盟",
            "id":"152900",
            "cityPinyin":"阿拉善盟",
            "lastModifyTime":null,
            "provinceId":"150000",
            "hotCity":false,
            "cityShortPY":"阿拉善盟"
        },
        {
            "name":"沈阳市",
            "id":"210100",
            "cityPinyin":"沈阳市",
            "lastModifyTime":null,
            "provinceId":"210000",
            "hotCity":false,
            "cityShortPY":"沈阳市"
        },
        {
            "name":"大连市",
            "id":"210200",
            "cityPinyin":"大连市",
            "lastModifyTime":null,
            "provinceId":"210000",
            "hotCity":false,
            "cityShortPY":"大连市"
        },
        {
            "name":"鞍山市",
            "id":"210300",
            "cityPinyin":"鞍山市",
            "lastModifyTime":null,
            "provinceId":"210000",
            "hotCity":false,
            "cityShortPY":"鞍山市"
        },
        {
            "name":"抚顺市",
            "id":"210400",
            "cityPinyin":"抚顺市",
            "lastModifyTime":null,
            "provinceId":"210000",
            "hotCity":false,
            "cityShortPY":"抚顺市"
        },
        {
            "name":"本溪市",
            "id":"210500",
            "cityPinyin":"本溪市",
            "lastModifyTime":null,
            "provinceId":"210000",
            "hotCity":false,
            "cityShortPY":"本溪市"
        },
        {
            "name":"丹东市",
            "id":"210600",
            "cityPinyin":"丹东市",
            "lastModifyTime":null,
            "provinceId":"210000",
            "hotCity":false,
            "cityShortPY":"丹东市"
        },
        {
            "name":"锦州市",
            "id":"210700",
            "cityPinyin":"锦州市",
            "lastModifyTime":null,
            "provinceId":"210000",
            "hotCity":false,
            "cityShortPY":"锦州市"
        },
        {
            "name":"营口市",
            "id":"210800",
            "cityPinyin":"营口市",
            "lastModifyTime":null,
            "provinceId":"210000",
            "hotCity":false,
            "cityShortPY":"营口市"
        },
        {
            "name":"阜新市",
            "id":"210900",
            "cityPinyin":"阜新市",
            "lastModifyTime":null,
            "provinceId":"210000",
            "hotCity":false,
            "cityShortPY":"阜新市"
        },
        {
            "name":"辽阳市",
            "id":"211000",
            "cityPinyin":"辽阳市",
            "lastModifyTime":null,
            "provinceId":"210000",
            "hotCity":false,
            "cityShortPY":"辽阳市"
        },
        {
            "name":"盘锦市",
            "id":"211100",
            "cityPinyin":"盘锦市",
            "lastModifyTime":null,
            "provinceId":"210000",
            "hotCity":false,
            "cityShortPY":"盘锦市"
        },
        {
            "name":"铁岭市",
            "id":"211200",
            "cityPinyin":"铁岭市",
            "lastModifyTime":null,
            "provinceId":"210000",
            "hotCity":false,
            "cityShortPY":"铁岭市"
        },
        {
            "name":"朝阳市",
            "id":"211300",
            "cityPinyin":"朝阳市",
            "lastModifyTime":null,
            "provinceId":"210000",
            "hotCity":false,
            "cityShortPY":"朝阳市"
        },
        {
            "name":"葫芦岛市",
            "id":"211400",
            "cityPinyin":"葫芦岛市",
            "lastModifyTime":null,
            "provinceId":"210000",
            "hotCity":false,
            "cityShortPY":"葫芦岛市"
        },
        {
            "name":"长沙",
            "id":"220100",
            "cityPinyin":"长沙",
            "lastModifyTime":null,
            "provinceId":"220000",
            "hotCity":false,
            "cityShortPY":"长沙"
        },
        {
            "name":"吉林市",
            "id":"220200",
            "cityPinyin":"吉林市",
            "lastModifyTime":null,
            "provinceId":"220000",
            "hotCity":false,
            "cityShortPY":"吉林市"
        },
        {
            "name":"四平市",
            "id":"220300",
            "cityPinyin":"四平市",
            "lastModifyTime":null,
            "provinceId":"220000",
            "hotCity":false,
            "cityShortPY":"四平市"
        },
        {
            "name":"辽源市",
            "id":"220400",
            "cityPinyin":"辽源市",
            "lastModifyTime":null,
            "provinceId":"220000",
            "hotCity":false,
            "cityShortPY":"辽源市"
        },
        {
            "name":"通化市",
            "id":"220500",
            "cityPinyin":"通化市",
            "lastModifyTime":null,
            "provinceId":"220000",
            "hotCity":false,
            "cityShortPY":"通化市"
        },
        {
            "name":"白山市",
            "id":"220600",
            "cityPinyin":"白山市",
            "lastModifyTime":null,
            "provinceId":"220000",
            "hotCity":false,
            "cityShortPY":"白山市"
        },
        {
            "name":"松原市",
            "id":"220700",
            "cityPinyin":"松原市",
            "lastModifyTime":null,
            "provinceId":"220000",
            "hotCity":false,
            "cityShortPY":"松原市"
        },
        {
            "name":"白城市",
            "id":"220800",
            "cityPinyin":"白城市",
            "lastModifyTime":null,
            "provinceId":"220000",
            "hotCity":false,
            "cityShortPY":"白城市"
        },
        {
            "name":"延边朝鲜族自治州",
            "id":"222400",
            "cityPinyin":"延边朝鲜族自治州",
            "lastModifyTime":null,
            "provinceId":"220000",
            "hotCity":false,
            "cityShortPY":"延边朝鲜族自治州"
        },
        {
            "name":"哈尔滨市",
            "id":"230100",
            "cityPinyin":"哈尔滨市",
            "lastModifyTime":null,
            "provinceId":"230000",
            "hotCity":false,
            "cityShortPY":"哈尔滨市"
        },
        {
            "name":"齐齐哈尔市",
            "id":"230200",
            "cityPinyin":"齐齐哈尔市",
            "lastModifyTime":null,
            "provinceId":"230000",
            "hotCity":false,
            "cityShortPY":"齐齐哈尔市"
        },
        {
            "name":"鸡西市",
            "id":"230300",
            "cityPinyin":"鸡西市",
            "lastModifyTime":null,
            "provinceId":"230000",
            "hotCity":false,
            "cityShortPY":"鸡西市"
        },
        {
            "name":"鹤岗市",
            "id":"230400",
            "cityPinyin":"鹤岗市",
            "lastModifyTime":null,
            "provinceId":"230000",
            "hotCity":false,
            "cityShortPY":"鹤岗市"
        },
        {
            "name":"双鸭山市",
            "id":"230500",
            "cityPinyin":"双鸭山市",
            "lastModifyTime":null,
            "provinceId":"230000",
            "hotCity":false,
            "cityShortPY":"双鸭山市"
        },
        {
            "name":"大庆市",
            "id":"230600",
            "cityPinyin":"大庆市",
            "lastModifyTime":null,
            "provinceId":"230000",
            "hotCity":false,
            "cityShortPY":"大庆市"
        },
        {
            "name":"伊春市",
            "id":"230700",
            "cityPinyin":"伊春市",
            "lastModifyTime":null,
            "provinceId":"230000",
            "hotCity":false,
            "cityShortPY":"伊春市"
        },
        {
            "name":"佳木斯市",
            "id":"230800",
            "cityPinyin":"佳木斯市",
            "lastModifyTime":null,
            "provinceId":"230000",
            "hotCity":false,
            "cityShortPY":"佳木斯市"
        },
        {
            "name":"七台河市",
            "id":"230900",
            "cityPinyin":"七台河市",
            "lastModifyTime":null,
            "provinceId":"230000",
            "hotCity":false,
            "cityShortPY":"七台河市"
        },
        {
            "name":"牡丹江市",
            "id":"231000",
            "cityPinyin":"牡丹江市",
            "lastModifyTime":null,
            "provinceId":"230000",
            "hotCity":false,
            "cityShortPY":"牡丹江市"
        },
        {
            "name":"黑河市",
            "id":"231100",
            "cityPinyin":"黑河市",
            "lastModifyTime":null,
            "provinceId":"230000",
            "hotCity":false,
            "cityShortPY":"黑河市"
        },
        {
            "name":"绥化市",
            "id":"231200",
            "cityPinyin":"绥化市",
            "lastModifyTime":null,
            "provinceId":"230000",
            "hotCity":false,
            "cityShortPY":"绥化市"
        },
        {
            "name":"大兴安岭地区",
            "id":"232700",
            "cityPinyin":"大兴安岭地区",
            "lastModifyTime":null,
            "provinceId":"230000",
            "hotCity":false,
            "cityShortPY":"大兴安岭地区"
        },
        {
            "name":"市辖区",
            "id":"310100",
            "cityPinyin":"市辖区",
            "lastModifyTime":null,
            "provinceId":"310000",
            "hotCity":false,
            "cityShortPY":"市辖区"
        },
        {
            "name":"县",
            "id":"310200",
            "cityPinyin":"县",
            "lastModifyTime":null,
            "provinceId":"310000",
            "hotCity":false,
            "cityShortPY":"县"
        },
        {
            "name":"南京市",
            "id":"320100",
            "cityPinyin":"南京市",
            "lastModifyTime":null,
            "provinceId":"320000",
            "hotCity":false,
            "cityShortPY":"南京市"
        },
        {
            "name":"无锡市",
            "id":"320202",
            "cityPinyin":"无锡市",
            "lastModifyTime":null,
            "provinceId":"320000",
            "hotCity":false,
            "cityShortPY":"无锡市"
        },
        {
            "name":"徐州市",
            "id":"320300",
            "cityPinyin":"徐州市",
            "lastModifyTime":null,
            "provinceId":"320000",
            "hotCity":false,
            "cityShortPY":"徐州市"
        },
        {
            "name":"常州市",
            "id":"320400",
            "cityPinyin":"常州市",
            "lastModifyTime":null,
            "provinceId":"320000",
            "hotCity":false,
            "cityShortPY":"常州市"
        },
        {
            "name":"苏州市",
            "id":"320500",
            "cityPinyin":"苏州市",
            "lastModifyTime":null,
            "provinceId":"320000",
            "hotCity":false,
            "cityShortPY":"苏州市"
        },
        {
            "name":"南通市",
            "id":"320600",
            "cityPinyin":"南通市",
            "lastModifyTime":null,
            "provinceId":"320000",
            "hotCity":false,
            "cityShortPY":"南通市"
        },
        {
            "name":"连云港市",
            "id":"320700",
            "cityPinyin":"连云港市",
            "lastModifyTime":null,
            "provinceId":"320000",
            "hotCity":false,
            "cityShortPY":"连云港市"
        },
        {
            "name":"淮安市",
            "id":"320800",
            "cityPinyin":"淮安市",
            "lastModifyTime":null,
            "provinceId":"320000",
            "hotCity":false,
            "cityShortPY":"淮安市"
        },
        {
            "name":"盐城市",
            "id":"320900",
            "cityPinyin":"盐城市",
            "lastModifyTime":null,
            "provinceId":"320000",
            "hotCity":false,
            "cityShortPY":"盐城市"
        },
        {
            "name":"扬州市",
            "id":"321000",
            "cityPinyin":"扬州市",
            "lastModifyTime":null,
            "provinceId":"320000",
            "hotCity":false,
            "cityShortPY":"扬州市"
        },
        {
            "name":"镇江市",
            "id":"321100",
            "cityPinyin":"镇江市",
            "lastModifyTime":null,
            "provinceId":"320000",
            "hotCity":false,
            "cityShortPY":"镇江市"
        },
        {
            "name":"泰州市",
            "id":"321200",
            "cityPinyin":"泰州市",
            "lastModifyTime":null,
            "provinceId":"320000",
            "hotCity":false,
            "cityShortPY":"泰州市"
        },
        {
            "name":"宿迁市",
            "id":"321300",
            "cityPinyin":"宿迁市",
            "lastModifyTime":null,
            "provinceId":"320000",
            "hotCity":false,
            "cityShortPY":"宿迁市"
        },
        {
            "name":"杭州市",
            "id":"330100",
            "cityPinyin":"杭州市",
            "lastModifyTime":null,
            "provinceId":"330000",
            "hotCity":false,
            "cityShortPY":"杭州市"
        },
        {
            "name":"宁波市",
            "id":"330200",
            "cityPinyin":"宁波市",
            "lastModifyTime":null,
            "provinceId":"330000",
            "hotCity":false,
            "cityShortPY":"宁波市"
        },
        {
            "name":"温州市",
            "id":"330300",
            "cityPinyin":"温州市",
            "lastModifyTime":null,
            "provinceId":"330000",
            "hotCity":false,
            "cityShortPY":"温州市"
        },
        {
            "name":"嘉兴市",
            "id":"330400",
            "cityPinyin":"嘉兴市",
            "lastModifyTime":null,
            "provinceId":"330000",
            "hotCity":false,
            "cityShortPY":"嘉兴市"
        },
        {
            "name":"湖州市",
            "id":"330500",
            "cityPinyin":"湖州市",
            "lastModifyTime":null,
            "provinceId":"330000",
            "hotCity":false,
            "cityShortPY":"湖州市"
        },
        {
            "name":"绍兴市",
            "id":"330600",
            "cityPinyin":"绍兴市",
            "lastModifyTime":null,
            "provinceId":"330000",
            "hotCity":false,
            "cityShortPY":"绍兴市"
        },
        {
            "name":"金华市",
            "id":"330700",
            "cityPinyin":"金华市",
            "lastModifyTime":null,
            "provinceId":"330000",
            "hotCity":false,
            "cityShortPY":"金华市"
        },
        {
            "name":"衢州市",
            "id":"330800",
            "cityPinyin":"衢州市",
            "lastModifyTime":null,
            "provinceId":"330000",
            "hotCity":false,
            "cityShortPY":"衢州市"
        },
        {
            "name":"舟山市",
            "id":"330900",
            "cityPinyin":"舟山市",
            "lastModifyTime":null,
            "provinceId":"330000",
            "hotCity":false,
            "cityShortPY":"舟山市"
        },
        {
            "name":"台州市",
            "id":"331000",
            "cityPinyin":"台州市",
            "lastModifyTime":null,
            "provinceId":"330000",
            "hotCity":false,
            "cityShortPY":"台州市"
        },
        {
            "name":"丽水市",
            "id":"331100",
            "cityPinyin":"丽水市",
            "lastModifyTime":null,
            "provinceId":"330000",
            "hotCity":false,
            "cityShortPY":"丽水市"
        },
        {
            "name":"合肥市",
            "id":"340100",
            "cityPinyin":"合肥市",
            "lastModifyTime":null,
            "provinceId":"340000",
            "hotCity":false,
            "cityShortPY":"合肥市"
        },
        {
            "name":"芜湖市",
            "id":"340200",
            "cityPinyin":"芜湖市",
            "lastModifyTime":null,
            "provinceId":"340000",
            "hotCity":false,
            "cityShortPY":"芜湖市"
        },
        {
            "name":"蚌埠市",
            "id":"340300",
            "cityPinyin":"蚌埠市",
            "lastModifyTime":null,
            "provinceId":"340000",
            "hotCity":false,
            "cityShortPY":"蚌埠市"
        },
        {
            "name":"淮南市",
            "id":"340400",
            "cityPinyin":"淮南市",
            "lastModifyTime":null,
            "provinceId":"340000",
            "hotCity":false,
            "cityShortPY":"淮南市"
        },
        {
            "name":"马鞍山市",
            "id":"340500",
            "cityPinyin":"马鞍山市",
            "lastModifyTime":null,
            "provinceId":"340000",
            "hotCity":false,
            "cityShortPY":"马鞍山市"
        },
        {
            "name":"淮北市",
            "id":"340600",
            "cityPinyin":"淮北市",
            "lastModifyTime":null,
            "provinceId":"340000",
            "hotCity":false,
            "cityShortPY":"淮北市"
        },
        {
            "name":"铜陵市",
            "id":"340700",
            "cityPinyin":"铜陵市",
            "lastModifyTime":null,
            "provinceId":"340000",
            "hotCity":false,
            "cityShortPY":"铜陵市"
        },
        {
            "name":"安庆市",
            "id":"340800",
            "cityPinyin":"安庆市",
            "lastModifyTime":null,
            "provinceId":"340000",
            "hotCity":false,
            "cityShortPY":"安庆市"
        },
        {
            "name":"黄山市",
            "id":"341000",
            "cityPinyin":"黄山市",
            "lastModifyTime":null,
            "provinceId":"340000",
            "hotCity":false,
            "cityShortPY":"黄山市"
        },
        {
            "name":"滁州市",
            "id":"341100",
            "cityPinyin":"滁州市",
            "lastModifyTime":null,
            "provinceId":"340000",
            "hotCity":false,
            "cityShortPY":"滁州市"
        },
        {
            "name":"阜阳市",
            "id":"341200",
            "cityPinyin":"阜阳市",
            "lastModifyTime":null,
            "provinceId":"340000",
            "hotCity":false,
            "cityShortPY":"阜阳市"
        },
        {
            "name":"宿州市",
            "id":"341300",
            "cityPinyin":"宿州市",
            "lastModifyTime":null,
            "provinceId":"340000",
            "hotCity":false,
            "cityShortPY":"宿州市"
        },
        {
            "name":"巢湖市",
            "id":"341400",
            "cityPinyin":"巢湖市",
            "lastModifyTime":null,
            "provinceId":"340000",
            "hotCity":false,
            "cityShortPY":"巢湖市"
        },
        {
            "name":"六安市",
            "id":"341500",
            "cityPinyin":"六安市",
            "lastModifyTime":null,
            "provinceId":"340000",
            "hotCity":false,
            "cityShortPY":"六安市"
        },
        {
            "name":"亳州市",
            "id":"341600",
            "cityPinyin":"亳州市",
            "lastModifyTime":null,
            "provinceId":"340000",
            "hotCity":false,
            "cityShortPY":"亳州市"
        },
        {
            "name":"池州市",
            "id":"341700",
            "cityPinyin":"池州市",
            "lastModifyTime":null,
            "provinceId":"340000",
            "hotCity":false,
            "cityShortPY":"池州市"
        },
        {
            "name":"宣城市",
            "id":"341800",
            "cityPinyin":"宣城市",
            "lastModifyTime":null,
            "provinceId":"340000",
            "hotCity":false,
            "cityShortPY":"宣城市"
        },
        {
            "name":"福州市",
            "id":"350100",
            "cityPinyin":"福州市",
            "lastModifyTime":null,
            "provinceId":"350000",
            "hotCity":false,
            "cityShortPY":"福州市"
        },
        {
            "name":"厦门市",
            "id":"350200",
            "cityPinyin":"厦门市",
            "lastModifyTime":null,
            "provinceId":"350000",
            "hotCity":false,
            "cityShortPY":"厦门市"
        },
        {
            "name":"莆田市",
            "id":"350300",
            "cityPinyin":"莆田市",
            "lastModifyTime":null,
            "provinceId":"350000",
            "hotCity":false,
            "cityShortPY":"莆田市"
        },
        {
            "name":"三明市",
            "id":"350400",
            "cityPinyin":"三明市",
            "lastModifyTime":null,
            "provinceId":"350000",
            "hotCity":false,
            "cityShortPY":"三明市"
        },
        {
            "name":"泉州市",
            "id":"350500",
            "cityPinyin":"泉州市",
            "lastModifyTime":null,
            "provinceId":"350000",
            "hotCity":false,
            "cityShortPY":"泉州市"
        },
        {
            "name":"漳州市",
            "id":"350600",
            "cityPinyin":"漳州市",
            "lastModifyTime":null,
            "provinceId":"350000",
            "hotCity":false,
            "cityShortPY":"漳州市"
        },
        {
            "name":"南平市",
            "id":"350700",
            "cityPinyin":"南平市",
            "lastModifyTime":null,
            "provinceId":"350000",
            "hotCity":false,
            "cityShortPY":"南平市"
        },
        {
            "name":"龙岩市",
            "id":"350800",
            "cityPinyin":"龙岩市",
            "lastModifyTime":null,
            "provinceId":"350000",
            "hotCity":false,
            "cityShortPY":"龙岩市"
        },
        {
            "name":"宁德市",
            "id":"350900",
            "cityPinyin":"宁德市",
            "lastModifyTime":null,
            "provinceId":"350000",
            "hotCity":false,
            "cityShortPY":"宁德市"
        },
        {
            "name":"南昌市",
            "id":"360100",
            "cityPinyin":"南昌市",
            "lastModifyTime":null,
            "provinceId":"360000",
            "hotCity":false,
            "cityShortPY":"南昌市"
        },
        {
            "name":"景德镇市",
            "id":"360200",
            "cityPinyin":"景德镇市",
            "lastModifyTime":null,
            "provinceId":"360000",
            "hotCity":false,
            "cityShortPY":"景德镇市"
        },
        {
            "name":"萍乡市",
            "id":"360300",
            "cityPinyin":"萍乡市",
            "lastModifyTime":null,
            "provinceId":"360000",
            "hotCity":false,
            "cityShortPY":"萍乡市"
        },
        {
            "name":"九江市",
            "id":"360400",
            "cityPinyin":"九江市",
            "lastModifyTime":null,
            "provinceId":"360000",
            "hotCity":false,
            "cityShortPY":"九江市"
        },
        {
            "name":"新余市",
            "id":"360500",
            "cityPinyin":"新余市",
            "lastModifyTime":null,
            "provinceId":"360000",
            "hotCity":false,
            "cityShortPY":"新余市"
        },
        {
            "name":"鹰潭市",
            "id":"360600",
            "cityPinyin":"鹰潭市",
            "lastModifyTime":null,
            "provinceId":"360000",
            "hotCity":false,
            "cityShortPY":"鹰潭市"
        },
        {
            "name":"赣州市",
            "id":"360700",
            "cityPinyin":"赣州市",
            "lastModifyTime":null,
            "provinceId":"360000",
            "hotCity":false,
            "cityShortPY":"赣州市"
        },
        {
            "name":"吉安市",
            "id":"360800",
            "cityPinyin":"吉安市",
            "lastModifyTime":null,
            "provinceId":"360000",
            "hotCity":false,
            "cityShortPY":"吉安市"
        },
        {
            "name":"宜春市",
            "id":"360900",
            "cityPinyin":"宜春市",
            "lastModifyTime":null,
            "provinceId":"360000",
            "hotCity":false,
            "cityShortPY":"宜春市"
        },
        {
            "name":"抚州市",
            "id":"361000",
            "cityPinyin":"抚州市",
            "lastModifyTime":null,
            "provinceId":"360000",
            "hotCity":false,
            "cityShortPY":"抚州市"
        },
        {
            "name":"上饶市",
            "id":"361100",
            "cityPinyin":"上饶市",
            "lastModifyTime":null,
            "provinceId":"360000",
            "hotCity":false,
            "cityShortPY":"上饶市"
        },
        {
            "name":"济南市",
            "id":"370100",
            "cityPinyin":"济南市",
            "lastModifyTime":null,
            "provinceId":"370000",
            "hotCity":false,
            "cityShortPY":"济南市"
        },
        {
            "name":"青岛市",
            "id":"370200",
            "cityPinyin":"青岛市",
            "lastModifyTime":null,
            "provinceId":"370000",
            "hotCity":false,
            "cityShortPY":"青岛市"
        },
        {
            "name":"淄博市",
            "id":"370300",
            "cityPinyin":"淄博市",
            "lastModifyTime":null,
            "provinceId":"370000",
            "hotCity":false,
            "cityShortPY":"淄博市"
        },
        {
            "name":"枣庄市",
            "id":"370400",
            "cityPinyin":"枣庄市",
            "lastModifyTime":null,
            "provinceId":"370000",
            "hotCity":false,
            "cityShortPY":"枣庄市"
        },
        {
            "name":"东营市",
            "id":"370500",
            "cityPinyin":"东营市",
            "lastModifyTime":null,
            "provinceId":"370000",
            "hotCity":false,
            "cityShortPY":"东营市"
        },
        {
            "name":"烟台市",
            "id":"370600",
            "cityPinyin":"烟台市",
            "lastModifyTime":null,
            "provinceId":"370000",
            "hotCity":false,
            "cityShortPY":"烟台市"
        },
        {
            "name":"潍坊市",
            "id":"370700",
            "cityPinyin":"潍坊市",
            "lastModifyTime":null,
            "provinceId":"370000",
            "hotCity":false,
            "cityShortPY":"潍坊市"
        },
        {
            "name":"济宁市",
            "id":"370800",
            "cityPinyin":"济宁市",
            "lastModifyTime":null,
            "provinceId":"370000",
            "hotCity":false,
            "cityShortPY":"济宁市"
        },
        {
            "name":"泰安市",
            "id":"370900",
            "cityPinyin":"泰安市",
            "lastModifyTime":null,
            "provinceId":"370000",
            "hotCity":false,
            "cityShortPY":"泰安市"
        },
        {
            "name":"威海市",
            "id":"371000",
            "cityPinyin":"威海市",
            "lastModifyTime":null,
            "provinceId":"370000",
            "hotCity":false,
            "cityShortPY":"威海市"
        },
        {
            "name":"日照市",
            "id":"371100",
            "cityPinyin":"日照市",
            "lastModifyTime":null,
            "provinceId":"370000",
            "hotCity":false,
            "cityShortPY":"日照市"
        },
        {
            "name":"莱芜市",
            "id":"371200",
            "cityPinyin":"莱芜市",
            "lastModifyTime":null,
            "provinceId":"370000",
            "hotCity":false,
            "cityShortPY":"莱芜市"
        },
        {
            "name":"临沂市",
            "id":"371300",
            "cityPinyin":"临沂市",
            "lastModifyTime":null,
            "provinceId":"370000",
            "hotCity":false,
            "cityShortPY":"临沂市"
        },
        {
            "name":"德州市",
            "id":"371400",
            "cityPinyin":"德州市",
            "lastModifyTime":null,
            "provinceId":"370000",
            "hotCity":false,
            "cityShortPY":"德州市"
        },
        {
            "name":"聊城市",
            "id":"371500",
            "cityPinyin":"聊城市",
            "lastModifyTime":null,
            "provinceId":"370000",
            "hotCity":false,
            "cityShortPY":"聊城市"
        },
        {
            "name":"滨州市",
            "id":"371600",
            "cityPinyin":"滨州市",
            "lastModifyTime":null,
            "provinceId":"370000",
            "hotCity":false,
            "cityShortPY":"滨州市"
        },
        {
            "name":"荷泽市",
            "id":"371700",
            "cityPinyin":"荷泽市",
            "lastModifyTime":null,
            "provinceId":"370000",
            "hotCity":false,
            "cityShortPY":"荷泽市"
        },
        {
            "name":"郑州市",
            "id":"410100",
            "cityPinyin":"郑州市",
            "lastModifyTime":null,
            "provinceId":"410000",
            "hotCity":false,
            "cityShortPY":"郑州市"
        },
        {
            "name":"开封市",
            "id":"410200",
            "cityPinyin":"开封市",
            "lastModifyTime":null,
            "provinceId":"410000",
            "hotCity":false,
            "cityShortPY":"开封市"
        },
        {
            "name":"洛阳市",
            "id":"410300",
            "cityPinyin":"洛阳市",
            "lastModifyTime":null,
            "provinceId":"410000",
            "hotCity":false,
            "cityShortPY":"洛阳市"
        },
        {
            "name":"平顶山市",
            "id":"410400",
            "cityPinyin":"平顶山市",
            "lastModifyTime":null,
            "provinceId":"410000",
            "hotCity":false,
            "cityShortPY":"平顶山市"
        },
        {
            "name":"安阳市",
            "id":"410500",
            "cityPinyin":"安阳市",
            "lastModifyTime":null,
            "provinceId":"410000",
            "hotCity":false,
            "cityShortPY":"安阳市"
        },
        {
            "name":"鹤壁市",
            "id":"410600",
            "cityPinyin":"鹤壁市",
            "lastModifyTime":null,
            "provinceId":"410000",
            "hotCity":false,
            "cityShortPY":"鹤壁市"
        },
        {
            "name":"新乡市",
            "id":"410700",
            "cityPinyin":"新乡市",
            "lastModifyTime":null,
            "provinceId":"410000",
            "hotCity":false,
            "cityShortPY":"新乡市"
        },
        {
            "name":"焦作市",
            "id":"410800",
            "cityPinyin":"焦作市",
            "lastModifyTime":null,
            "provinceId":"410000",
            "hotCity":false,
            "cityShortPY":"焦作市"
        },
        {
            "name":"濮阳市",
            "id":"410900",
            "cityPinyin":"濮阳市",
            "lastModifyTime":null,
            "provinceId":"410000",
            "hotCity":false,
            "cityShortPY":"濮阳市"
        },
        {
            "name":"许昌市",
            "id":"411000",
            "cityPinyin":"许昌市",
            "lastModifyTime":null,
            "provinceId":"410000",
            "hotCity":false,
            "cityShortPY":"许昌市"
        },
        {
            "name":"漯河市",
            "id":"411100",
            "cityPinyin":"漯河市",
            "lastModifyTime":null,
            "provinceId":"410000",
            "hotCity":false,
            "cityShortPY":"漯河市"
        },
        {
            "name":"三门峡市",
            "id":"411200",
            "cityPinyin":"三门峡市",
            "lastModifyTime":null,
            "provinceId":"410000",
            "hotCity":false,
            "cityShortPY":"三门峡市"
        },
        {
            "name":"南阳市",
            "id":"411300",
            "cityPinyin":"南阳市",
            "lastModifyTime":null,
            "provinceId":"410000",
            "hotCity":false,
            "cityShortPY":"南阳市"
        },
        {
            "name":"商丘市",
            "id":"411400",
            "cityPinyin":"商丘市",
            "lastModifyTime":null,
            "provinceId":"410000",
            "hotCity":false,
            "cityShortPY":"商丘市"
        },
        {
            "name":"信阳市",
            "id":"411500",
            "cityPinyin":"信阳市",
            "lastModifyTime":null,
            "provinceId":"410000",
            "hotCity":false,
            "cityShortPY":"信阳市"
        },
        {
            "name":"周口市",
            "id":"411600",
            "cityPinyin":"周口市",
            "lastModifyTime":null,
            "provinceId":"410000",
            "hotCity":false,
            "cityShortPY":"周口市"
        },
        {
            "name":"驻马店市",
            "id":"411700",
            "cityPinyin":"驻马店市",
            "lastModifyTime":null,
            "provinceId":"410000",
            "hotCity":false,
            "cityShortPY":"驻马店市"
        },
        {
            "name":"武汉市",
            "id":"420100",
            "cityPinyin":"武汉市",
            "lastModifyTime":null,
            "provinceId":"420000",
            "hotCity":true,
            "cityShortPY":"武汉市"
        },
        {
            "name":"黄石市",
            "id":"420200",
            "cityPinyin":"黄石市",
            "lastModifyTime":null,
            "provinceId":"420000",
            "hotCity":false,
            "cityShortPY":"黄石市"
        },
        {
            "name":"十堰市",
            "id":"420300",
            "cityPinyin":"十堰市",
            "lastModifyTime":null,
            "provinceId":"420000",
            "hotCity":false,
            "cityShortPY":"十堰市"
        },
        {
            "name":"宜昌市",
            "id":"420500",
            "cityPinyin":"宜昌市",
            "lastModifyTime":null,
            "provinceId":"420000",
            "hotCity":false,
            "cityShortPY":"宜昌市"
        },
        {
            "name":"襄樊市",
            "id":"420600",
            "cityPinyin":"襄樊市",
            "lastModifyTime":null,
            "provinceId":"420000",
            "hotCity":false,
            "cityShortPY":"襄樊市"
        },
        {
            "name":"鄂州市",
            "id":"420700",
            "cityPinyin":"鄂州市",
            "lastModifyTime":null,
            "provinceId":"420000",
            "hotCity":false,
            "cityShortPY":"鄂州市"
        },
        {
            "name":"荆门市",
            "id":"420800",
            "cityPinyin":"荆门市",
            "lastModifyTime":null,
            "provinceId":"420000",
            "hotCity":false,
            "cityShortPY":"荆门市"
        },
        {
            "name":"孝感市",
            "id":"420900",
            "cityPinyin":"孝感市",
            "lastModifyTime":null,
            "provinceId":"420000",
            "hotCity":false,
            "cityShortPY":"孝感市"
        },
        {
            "name":"荆州市",
            "id":"421000",
            "cityPinyin":"荆州市",
            "lastModifyTime":null,
            "provinceId":"420000",
            "hotCity":false,
            "cityShortPY":"荆州市"
        },
        {
            "name":"黄冈市",
            "id":"421100",
            "cityPinyin":"黄冈市",
            "lastModifyTime":null,
            "provinceId":"420000",
            "hotCity":false,
            "cityShortPY":"黄冈市"
        },
        {
            "name":"咸宁市",
            "id":"421200",
            "cityPinyin":"咸宁市",
            "lastModifyTime":null,
            "provinceId":"420000",
            "hotCity":false,
            "cityShortPY":"咸宁市"
        },
        {
            "name":"随州市",
            "id":"421300",
            "cityPinyin":"随州市",
            "lastModifyTime":null,
            "provinceId":"420000",
            "hotCity":false,
            "cityShortPY":"随州市"
        },
        {
            "name":"恩施土家族苗族自治州",
            "id":"422800",
            "cityPinyin":"恩施土家族苗族自治州",
            "lastModifyTime":null,
            "provinceId":"420000",
            "hotCity":false,
            "cityShortPY":"恩施土家族苗族自治州"
        },
        {
            "name":"省直辖行政单位",
            "id":"429000",
            "cityPinyin":"省直辖行政单位",
            "lastModifyTime":null,
            "provinceId":"420000",
            "hotCity":false,
            "cityShortPY":"省直辖行政单位"
        },
        {
            "name":"长沙市",
            "id":"430100",
            "cityPinyin":"长沙市",
            "lastModifyTime":null,
            "provinceId":"430000",
            "hotCity":false,
            "cityShortPY":"长沙市"
        },
        {
            "name":"株洲市",
            "id":"430200",
            "cityPinyin":"株洲市",
            "lastModifyTime":null,
            "provinceId":"430000",
            "hotCity":false,
            "cityShortPY":"株洲市"
        },
        {
            "name":"湘潭市",
            "id":"430300",
            "cityPinyin":"湘潭市",
            "lastModifyTime":null,
            "provinceId":"430000",
            "hotCity":false,
            "cityShortPY":"湘潭市"
        },
        {
            "name":"衡阳市",
            "id":"430400",
            "cityPinyin":"衡阳市",
            "lastModifyTime":null,
            "provinceId":"430000",
            "hotCity":false,
            "cityShortPY":"衡阳市"
        },
        {
            "name":"邵阳市",
            "id":"430500",
            "cityPinyin":"邵阳市",
            "lastModifyTime":null,
            "provinceId":"430000",
            "hotCity":false,
            "cityShortPY":"邵阳市"
        },
        {
            "name":"岳阳市",
            "id":"430600",
            "cityPinyin":"岳阳市",
            "lastModifyTime":null,
            "provinceId":"430000",
            "hotCity":false,
            "cityShortPY":"岳阳市"
        },
        {
            "name":"常德市",
            "id":"430700",
            "cityPinyin":"常德市",
            "lastModifyTime":null,
            "provinceId":"430000",
            "hotCity":false,
            "cityShortPY":"常德市"
        },
        {
            "name":"张家界市",
            "id":"430800",
            "cityPinyin":"张家界市",
            "lastModifyTime":null,
            "provinceId":"430000",
            "hotCity":false,
            "cityShortPY":"张家界市"
        },
        {
            "name":"益阳市",
            "id":"430900",
            "cityPinyin":"益阳市",
            "lastModifyTime":null,
            "provinceId":"430000",
            "hotCity":false,
            "cityShortPY":"益阳市"
        },
        {
            "name":"郴州市",
            "id":"431000",
            "cityPinyin":"郴州市",
            "lastModifyTime":null,
            "provinceId":"430000",
            "hotCity":false,
            "cityShortPY":"郴州市"
        },
        {
            "name":"永州市",
            "id":"431100",
            "cityPinyin":"永州市",
            "lastModifyTime":null,
            "provinceId":"430000",
            "hotCity":false,
            "cityShortPY":"永州市"
        },
        {
            "name":"怀化市",
            "id":"431200",
            "cityPinyin":"怀化市",
            "lastModifyTime":null,
            "provinceId":"430000",
            "hotCity":false,
            "cityShortPY":"怀化市"
        },
        {
            "name":"娄底市",
            "id":"431300",
            "cityPinyin":"娄底市",
            "lastModifyTime":null,
            "provinceId":"430000",
            "hotCity":false,
            "cityShortPY":"娄底市"
        },
        {
            "name":"湘西土家族苗族自治州",
            "id":"433100",
            "cityPinyin":"湘西土家族苗族自治州",
            "lastModifyTime":null,
            "provinceId":"430000",
            "hotCity":false,
            "cityShortPY":"湘西土家族苗族自治州"
        },
        {
            "name":"广州市",
            "id":"440100",
            "cityPinyin":"广州市",
            "lastModifyTime":null,
            "provinceId":"440000",
            "hotCity":false,
            "cityShortPY":"广州市"
        },
        {
            "name":"韶关市",
            "id":"440200",
            "cityPinyin":"韶关市",
            "lastModifyTime":null,
            "provinceId":"440000",
            "hotCity":false,
            "cityShortPY":"韶关市"
        },
        {
            "name":"深圳市",
            "id":"440300",
            "cityPinyin":"深圳市",
            "lastModifyTime":null,
            "provinceId":"440000",
            "hotCity":false,
            "cityShortPY":"深圳市"
        },
        {
            "name":"珠海市",
            "id":"440400",
            "cityPinyin":"珠海市",
            "lastModifyTime":null,
            "provinceId":"440000",
            "hotCity":false,
            "cityShortPY":"珠海市"
        },
        {
            "name":"汕头市",
            "id":"440500",
            "cityPinyin":"汕头市",
            "lastModifyTime":null,
            "provinceId":"440000",
            "hotCity":false,
            "cityShortPY":"汕头市"
        },
        {
            "name":"佛山市",
            "id":"440600",
            "cityPinyin":"佛山市",
            "lastModifyTime":null,
            "provinceId":"440000",
            "hotCity":false,
            "cityShortPY":"佛山市"
        },
        {
            "name":"江门市",
            "id":"440700",
            "cityPinyin":"江门市",
            "lastModifyTime":null,
            "provinceId":"440000",
            "hotCity":false,
            "cityShortPY":"江门市"
        },
        {
            "name":"湛江市",
            "id":"440800",
            "cityPinyin":"湛江市",
            "lastModifyTime":null,
            "provinceId":"440000",
            "hotCity":false,
            "cityShortPY":"湛江市"
        },
        {
            "name":"茂名市",
            "id":"440900",
            "cityPinyin":"茂名市",
            "lastModifyTime":null,
            "provinceId":"440000",
            "hotCity":false,
            "cityShortPY":"茂名市"
        },
        {
            "name":"肇庆市",
            "id":"441200",
            "cityPinyin":"肇庆市",
            "lastModifyTime":null,
            "provinceId":"440000",
            "hotCity":false,
            "cityShortPY":"肇庆市"
        },
        {
            "name":"惠州市",
            "id":"441300",
            "cityPinyin":"惠州市",
            "lastModifyTime":null,
            "provinceId":"440000",
            "hotCity":false,
            "cityShortPY":"惠州市"
        },
        {
            "name":"梅州市",
            "id":"441400",
            "cityPinyin":"梅州市",
            "lastModifyTime":null,
            "provinceId":"440000",
            "hotCity":false,
            "cityShortPY":"梅州市"
        },
        {
            "name":"汕尾市",
            "id":"441500",
            "cityPinyin":"汕尾市",
            "lastModifyTime":null,
            "provinceId":"440000",
            "hotCity":false,
            "cityShortPY":"汕尾市"
        },
        {
            "name":"河源市",
            "id":"441600",
            "cityPinyin":"河源市",
            "lastModifyTime":null,
            "provinceId":"440000",
            "hotCity":false,
            "cityShortPY":"河源市"
        },
        {
            "name":"阳江市",
            "id":"441700",
            "cityPinyin":"阳江市",
            "lastModifyTime":null,
            "provinceId":"440000",
            "hotCity":false,
            "cityShortPY":"阳江市"
        },
        {
            "name":"清远市",
            "id":"441800",
            "cityPinyin":"清远市",
            "lastModifyTime":null,
            "provinceId":"440000",
            "hotCity":false,
            "cityShortPY":"清远市"
        },
        {
            "name":"东莞市",
            "id":"441900",
            "cityPinyin":"东莞市",
            "lastModifyTime":null,
            "provinceId":"440000",
            "hotCity":false,
            "cityShortPY":"东莞市"
        },
        {
            "name":"中山市",
            "id":"442000",
            "cityPinyin":"中山市",
            "lastModifyTime":null,
            "provinceId":"440000",
            "hotCity":false,
            "cityShortPY":"中山市"
        },
        {
            "name":"潮州市",
            "id":"445100",
            "cityPinyin":"潮州市",
            "lastModifyTime":null,
            "provinceId":"440000",
            "hotCity":false,
            "cityShortPY":"潮州市"
        },
        {
            "name":"揭阳市",
            "id":"445200",
            "cityPinyin":"揭阳市",
            "lastModifyTime":null,
            "provinceId":"440000",
            "hotCity":false,
            "cityShortPY":"揭阳市"
        },
        {
            "name":"云浮市",
            "id":"445300",
            "cityPinyin":"云浮市",
            "lastModifyTime":null,
            "provinceId":"440000",
            "hotCity":false,
            "cityShortPY":"云浮市"
        },
        {
            "name":"玉林市",
            "id":"450900",
            "cityPinyin":"玉林市",
            "lastModifyTime":null,
            "provinceId":"450000",
            "hotCity":true,
            "cityShortPY":"玉林市"
        },
        {
            "name":"南宁市",
            "id":"450100",
            "cityPinyin":"南宁市",
            "lastModifyTime":null,
            "provinceId":"450000",
            "hotCity":false,
            "cityShortPY":"南宁市"
        },
        {
            "name":"柳州市",
            "id":"450200",
            "cityPinyin":"柳州市",
            "lastModifyTime":null,
            "provinceId":"450000",
            "hotCity":false,
            "cityShortPY":"柳州市"
        },
        {
            "name":"桂林市",
            "id":"450300",
            "cityPinyin":"桂林市",
            "lastModifyTime":null,
            "provinceId":"450000",
            "hotCity":false,
            "cityShortPY":"桂林市"
        },
        {
            "name":"梧州市",
            "id":"450400",
            "cityPinyin":"梧州市",
            "lastModifyTime":null,
            "provinceId":"450000",
            "hotCity":false,
            "cityShortPY":"梧州市"
        },
        {
            "name":"北海市",
            "id":"450500",
            "cityPinyin":"北海市",
            "lastModifyTime":null,
            "provinceId":"450000",
            "hotCity":false,
            "cityShortPY":"北海市"
        },
        {
            "name":"防城港市",
            "id":"450600",
            "cityPinyin":"防城港市",
            "lastModifyTime":null,
            "provinceId":"450000",
            "hotCity":false,
            "cityShortPY":"防城港市"
        },
        {
            "name":"钦州市",
            "id":"450700",
            "cityPinyin":"钦州市",
            "lastModifyTime":null,
            "provinceId":"450000",
            "hotCity":false,
            "cityShortPY":"钦州市"
        },
        {
            "name":"贵港市",
            "id":"450800",
            "cityPinyin":"贵港市",
            "lastModifyTime":null,
            "provinceId":"450000",
            "hotCity":false,
            "cityShortPY":"贵港市"
        },
        {
            "name":"百色市",
            "id":"451000",
            "cityPinyin":"百色市",
            "lastModifyTime":null,
            "provinceId":"450000",
            "hotCity":false,
            "cityShortPY":"百色市"
        },
        {
            "name":"贺州市",
            "id":"451100",
            "cityPinyin":"贺州市",
            "lastModifyTime":null,
            "provinceId":"450000",
            "hotCity":false,
            "cityShortPY":"贺州市"
        },
        {
            "name":"河池市",
            "id":"451200",
            "cityPinyin":"河池市",
            "lastModifyTime":null,
            "provinceId":"450000",
            "hotCity":false,
            "cityShortPY":"河池市"
        },
        {
            "name":"来宾市",
            "id":"451300",
            "cityPinyin":"来宾市",
            "lastModifyTime":null,
            "provinceId":"450000",
            "hotCity":false,
            "cityShortPY":"来宾市"
        },
        {
            "name":"崇左市",
            "id":"451400",
            "cityPinyin":"崇左市",
            "lastModifyTime":null,
            "provinceId":"450000",
            "hotCity":false,
            "cityShortPY":"崇左市"
        },
        {
            "name":"海口市",
            "id":"460100",
            "cityPinyin":"海口市",
            "lastModifyTime":null,
            "provinceId":"460000",
            "hotCity":false,
            "cityShortPY":"海口市"
        },
        {
            "name":"三亚市",
            "id":"460200",
            "cityPinyin":"三亚市",
            "lastModifyTime":null,
            "provinceId":"460000",
            "hotCity":false,
            "cityShortPY":"三亚市"
        },
        {
            "name":"省直辖县级行政单位",
            "id":"469000",
            "cityPinyin":"省直辖县级行政单位",
            "lastModifyTime":null,
            "provinceId":"460000",
            "hotCity":false,
            "cityShortPY":"省直辖县级行政单位"
        },
        {
            "name":"市辖区",
            "id":"500100",
            "cityPinyin":"市辖区",
            "lastModifyTime":null,
            "provinceId":"500000",
            "hotCity":false,
            "cityShortPY":"市辖区"
        },
        {
            "name":"县",
            "id":"500200",
            "cityPinyin":"县",
            "lastModifyTime":null,
            "provinceId":"500000",
            "hotCity":false,
            "cityShortPY":"县"
        },
        {
            "name":"市",
            "id":"500300",
            "cityPinyin":"市",
            "lastModifyTime":null,
            "provinceId":"500000",
            "hotCity":false,
            "cityShortPY":"市"
        },
        {
            "name":"成都市",
            "id":"510100",
            "cityPinyin":"成都市",
            "lastModifyTime":null,
            "provinceId":"510000",
            "hotCity":false,
            "cityShortPY":"成都市"
        },
        {
            "name":"自贡市",
            "id":"510300",
            "cityPinyin":"自贡市",
            "lastModifyTime":null,
            "provinceId":"510000",
            "hotCity":false,
            "cityShortPY":"自贡市"
        },
        {
            "name":"攀枝花市",
            "id":"510400",
            "cityPinyin":"攀枝花市",
            "lastModifyTime":null,
            "provinceId":"510000",
            "hotCity":false,
            "cityShortPY":"攀枝花市"
        },
        {
            "name":"泸州市",
            "id":"510500",
            "cityPinyin":"泸州市",
            "lastModifyTime":null,
            "provinceId":"510000",
            "hotCity":false,
            "cityShortPY":"泸州市"
        },
        {
            "name":"德阳市",
            "id":"510600",
            "cityPinyin":"德阳市",
            "lastModifyTime":null,
            "provinceId":"510000",
            "hotCity":false,
            "cityShortPY":"德阳市"
        },
        {
            "name":"绵阳市",
            "id":"510700",
            "cityPinyin":"绵阳市",
            "lastModifyTime":null,
            "provinceId":"510000",
            "hotCity":false,
            "cityShortPY":"绵阳市"
        },
        {
            "name":"广元市",
            "id":"510800",
            "cityPinyin":"广元市",
            "lastModifyTime":null,
            "provinceId":"510000",
            "hotCity":false,
            "cityShortPY":"广元市"
        },
        {
            "name":"遂宁市",
            "id":"510900",
            "cityPinyin":"遂宁市",
            "lastModifyTime":null,
            "provinceId":"510000",
            "hotCity":false,
            "cityShortPY":"遂宁市"
        },
        {
            "name":"内江市",
            "id":"511000",
            "cityPinyin":"内江市",
            "lastModifyTime":null,
            "provinceId":"510000",
            "hotCity":false,
            "cityShortPY":"内江市"
        },
        {
            "name":"乐山市",
            "id":"511100",
            "cityPinyin":"乐山市",
            "lastModifyTime":null,
            "provinceId":"510000",
            "hotCity":false,
            "cityShortPY":"乐山市"
        },
        {
            "name":"南充市",
            "id":"511300",
            "cityPinyin":"南充市",
            "lastModifyTime":null,
            "provinceId":"510000",
            "hotCity":false,
            "cityShortPY":"南充市"
        },
        {
            "name":"眉山市",
            "id":"511400",
            "cityPinyin":"眉山市",
            "lastModifyTime":null,
            "provinceId":"510000",
            "hotCity":false,
            "cityShortPY":"眉山市"
        },
        {
            "name":"宜宾市",
            "id":"511500",
            "cityPinyin":"宜宾市",
            "lastModifyTime":null,
            "provinceId":"510000",
            "hotCity":false,
            "cityShortPY":"宜宾市"
        },
        {
            "name":"广安市",
            "id":"511600",
            "cityPinyin":"广安市",
            "lastModifyTime":null,
            "provinceId":"510000",
            "hotCity":false,
            "cityShortPY":"广安市"
        },
        {
            "name":"达州市",
            "id":"511700",
            "cityPinyin":"达州市",
            "lastModifyTime":null,
            "provinceId":"510000",
            "hotCity":false,
            "cityShortPY":"达州市"
        },
        {
            "name":"雅安市",
            "id":"511800",
            "cityPinyin":"雅安市",
            "lastModifyTime":null,
            "provinceId":"510000",
            "hotCity":false,
            "cityShortPY":"雅安市"
        },
        {
            "name":"巴中市",
            "id":"511900",
            "cityPinyin":"巴中市",
            "lastModifyTime":null,
            "provinceId":"510000",
            "hotCity":false,
            "cityShortPY":"巴中市"
        },
        {
            "name":"资阳市",
            "id":"512000",
            "cityPinyin":"资阳市",
            "lastModifyTime":null,
            "provinceId":"510000",
            "hotCity":false,
            "cityShortPY":"资阳市"
        },
        {
            "name":"阿坝藏族羌族自治州",
            "id":"513200",
            "cityPinyin":"阿坝藏族羌族自治州",
            "lastModifyTime":null,
            "provinceId":"510000",
            "hotCity":false,
            "cityShortPY":"阿坝藏族羌族自治州"
        },
        {
            "name":"甘孜藏族自治州",
            "id":"513300",
            "cityPinyin":"甘孜藏族自治州",
            "lastModifyTime":null,
            "provinceId":"510000",
            "hotCity":false,
            "cityShortPY":"甘孜藏族自治州"
        },
        {
            "name":"凉山彝族自治州",
            "id":"513400",
            "cityPinyin":"凉山彝族自治州",
            "lastModifyTime":null,
            "provinceId":"510000",
            "hotCity":false,
            "cityShortPY":"凉山彝族自治州"
        },
        {
            "name":"贵阳市",
            "id":"520100",
            "cityPinyin":"贵阳市",
            "lastModifyTime":null,
            "provinceId":"520000",
            "hotCity":false,
            "cityShortPY":"贵阳市"
        },
        {
            "name":"六盘水市",
            "id":"520200",
            "cityPinyin":"六盘水市",
            "lastModifyTime":null,
            "provinceId":"520000",
            "hotCity":false,
            "cityShortPY":"六盘水市"
        },
        {
            "name":"遵义市",
            "id":"520300",
            "cityPinyin":"遵义市",
            "lastModifyTime":null,
            "provinceId":"520000",
            "hotCity":false,
            "cityShortPY":"遵义市"
        },
        {
            "name":"安顺市",
            "id":"520400",
            "cityPinyin":"安顺市",
            "lastModifyTime":null,
            "provinceId":"520000",
            "hotCity":false,
            "cityShortPY":"安顺市"
        },
        {
            "name":"铜仁地区",
            "id":"522200",
            "cityPinyin":"铜仁地区",
            "lastModifyTime":null,
            "provinceId":"520000",
            "hotCity":false,
            "cityShortPY":"铜仁地区"
        },
        {
            "name":"黔西南布依族苗族自治州",
            "id":"522300",
            "cityPinyin":"黔西南布依族苗族自治州",
            "lastModifyTime":null,
            "provinceId":"520000",
            "hotCity":false,
            "cityShortPY":"黔西南布依族苗族自治州"
        },
        {
            "name":"毕节地区",
            "id":"522400",
            "cityPinyin":"毕节地区",
            "lastModifyTime":null,
            "provinceId":"520000",
            "hotCity":false,
            "cityShortPY":"毕节地区"
        },
        {
            "name":"黔东南苗族侗族自治州",
            "id":"522600",
            "cityPinyin":"黔东南苗族侗族自治州",
            "lastModifyTime":null,
            "provinceId":"520000",
            "hotCity":false,
            "cityShortPY":"黔东南苗族侗族自治州"
        },
        {
            "name":"黔南布依族苗族自治州",
            "id":"522700",
            "cityPinyin":"黔南布依族苗族自治州",
            "lastModifyTime":null,
            "provinceId":"520000",
            "hotCity":false,
            "cityShortPY":"黔南布依族苗族自治州"
        },
        {
            "name":"昆明市",
            "id":"530100",
            "cityPinyin":"昆明市",
            "lastModifyTime":null,
            "provinceId":"530000",
            "hotCity":false,
            "cityShortPY":"昆明市"
        },
        {
            "name":"曲靖市",
            "id":"530300",
            "cityPinyin":"曲靖市",
            "lastModifyTime":null,
            "provinceId":"530000",
            "hotCity":false,
            "cityShortPY":"曲靖市"
        },
        {
            "name":"玉溪市",
            "id":"530400",
            "cityPinyin":"玉溪市",
            "lastModifyTime":null,
            "provinceId":"530000",
            "hotCity":false,
            "cityShortPY":"玉溪市"
        },
        {
            "name":"保山市",
            "id":"530500",
            "cityPinyin":"保山市",
            "lastModifyTime":null,
            "provinceId":"530000",
            "hotCity":false,
            "cityShortPY":"保山市"
        },
        {
            "name":"昭通市",
            "id":"530600",
            "cityPinyin":"昭通市",
            "lastModifyTime":null,
            "provinceId":"530000",
            "hotCity":false,
            "cityShortPY":"昭通市"
        },
        {
            "name":"丽江市",
            "id":"530700",
            "cityPinyin":"丽江市",
            "lastModifyTime":null,
            "provinceId":"530000",
            "hotCity":false,
            "cityShortPY":"丽江市"
        },
        {
            "name":"思茅市",
            "id":"530800",
            "cityPinyin":"思茅市",
            "lastModifyTime":null,
            "provinceId":"530000",
            "hotCity":false,
            "cityShortPY":"思茅市"
        },
        {
            "name":"临沧市",
            "id":"530900",
            "cityPinyin":"临沧市",
            "lastModifyTime":null,
            "provinceId":"530000",
            "hotCity":false,
            "cityShortPY":"临沧市"
        },
        {
            "name":"楚雄彝族自治州",
            "id":"532300",
            "cityPinyin":"楚雄彝族自治州",
            "lastModifyTime":null,
            "provinceId":"530000",
            "hotCity":false,
            "cityShortPY":"楚雄彝族自治州"
        },
        {
            "name":"红河哈尼族彝族自治州",
            "id":"532500",
            "cityPinyin":"红河哈尼族彝族自治州",
            "lastModifyTime":null,
            "provinceId":"530000",
            "hotCity":false,
            "cityShortPY":"红河哈尼族彝族自治州"
        },
        {
            "name":"文山壮族苗族自治州",
            "id":"532600",
            "cityPinyin":"文山壮族苗族自治州",
            "lastModifyTime":null,
            "provinceId":"530000",
            "hotCity":false,
            "cityShortPY":"文山壮族苗族自治州"
        },
        {
            "name":"西双版纳傣族自治州",
            "id":"532800",
            "cityPinyin":"西双版纳傣族自治州",
            "lastModifyTime":null,
            "provinceId":"530000",
            "hotCity":false,
            "cityShortPY":"西双版纳傣族自治州"
        },
        {
            "name":"大理白族自治州",
            "id":"532900",
            "cityPinyin":"大理白族自治州",
            "lastModifyTime":null,
            "provinceId":"530000",
            "hotCity":false,
            "cityShortPY":"大理白族自治州"
        },
        {
            "name":"德宏傣族景颇族自治州",
            "id":"533100",
            "cityPinyin":"德宏傣族景颇族自治州",
            "lastModifyTime":null,
            "provinceId":"530000",
            "hotCity":false,
            "cityShortPY":"德宏傣族景颇族自治州"
        },
        {
            "name":"怒江傈僳族自治州",
            "id":"533300",
            "cityPinyin":"怒江傈僳族自治州",
            "lastModifyTime":null,
            "provinceId":"530000",
            "hotCity":false,
            "cityShortPY":"怒江傈僳族自治州"
        },
        {
            "name":"迪庆藏族自治州",
            "id":"533400",
            "cityPinyin":"迪庆藏族自治州",
            "lastModifyTime":null,
            "provinceId":"530000",
            "hotCity":false,
            "cityShortPY":"迪庆藏族自治州"
        },
        {
            "name":"拉萨市",
            "id":"540100",
            "cityPinyin":"拉萨市",
            "lastModifyTime":null,
            "provinceId":"540000",
            "hotCity":false,
            "cityShortPY":"拉萨市"
        },
        {
            "name":"昌都地区",
            "id":"542100",
            "cityPinyin":"昌都地区",
            "lastModifyTime":null,
            "provinceId":"540000",
            "hotCity":false,
            "cityShortPY":"昌都地区"
        },
        {
            "name":"山南地区",
            "id":"542200",
            "cityPinyin":"山南地区",
            "lastModifyTime":null,
            "provinceId":"540000",
            "hotCity":false,
            "cityShortPY":"山南地区"
        },
        {
            "name":"日喀则地区",
            "id":"542300",
            "cityPinyin":"日喀则地区",
            "lastModifyTime":null,
            "provinceId":"540000",
            "hotCity":false,
            "cityShortPY":"日喀则地区"
        },
        {
            "name":"那曲地区",
            "id":"542400",
            "cityPinyin":"那曲地区",
            "lastModifyTime":null,
            "provinceId":"540000",
            "hotCity":false,
            "cityShortPY":"那曲地区"
        },
        {
            "name":"阿里地区",
            "id":"542500",
            "cityPinyin":"阿里地区",
            "lastModifyTime":null,
            "provinceId":"540000",
            "hotCity":false,
            "cityShortPY":"阿里地区"
        },
        {
            "name":"林芝地区",
            "id":"542600",
            "cityPinyin":"林芝地区",
            "lastModifyTime":null,
            "provinceId":"540000",
            "hotCity":false,
            "cityShortPY":"林芝地区"
        },
        {
            "name":"西安市",
            "id":"610100",
            "cityPinyin":"西安市",
            "lastModifyTime":null,
            "provinceId":"610000",
            "hotCity":false,
            "cityShortPY":"西安市"
        },
        {
            "name":"铜川市",
            "id":"610200",
            "cityPinyin":"铜川市",
            "lastModifyTime":null,
            "provinceId":"610000",
            "hotCity":false,
            "cityShortPY":"铜川市"
        },
        {
            "name":"宝鸡市",
            "id":"610300",
            "cityPinyin":"宝鸡市",
            "lastModifyTime":null,
            "provinceId":"610000",
            "hotCity":false,
            "cityShortPY":"宝鸡市"
        },
        {
            "name":"咸阳市",
            "id":"610400",
            "cityPinyin":"咸阳市",
            "lastModifyTime":null,
            "provinceId":"610000",
            "hotCity":false,
            "cityShortPY":"咸阳市"
        },
        {
            "name":"渭南市",
            "id":"610500",
            "cityPinyin":"渭南市",
            "lastModifyTime":null,
            "provinceId":"610000",
            "hotCity":false,
            "cityShortPY":"渭南市"
        },
        {
            "name":"延安市",
            "id":"610600",
            "cityPinyin":"延安市",
            "lastModifyTime":null,
            "provinceId":"610000",
            "hotCity":false,
            "cityShortPY":"延安市"
        },
        {
            "name":"汉中市",
            "id":"610700",
            "cityPinyin":"汉中市",
            "lastModifyTime":null,
            "provinceId":"610000",
            "hotCity":false,
            "cityShortPY":"汉中市"
        },
        {
            "name":"榆林市",
            "id":"610800",
            "cityPinyin":"榆林市",
            "lastModifyTime":null,
            "provinceId":"610000",
            "hotCity":false,
            "cityShortPY":"榆林市"
        },
        {
            "name":"安康市",
            "id":"610900",
            "cityPinyin":"安康市",
            "lastModifyTime":null,
            "provinceId":"610000",
            "hotCity":false,
            "cityShortPY":"安康市"
        },
        {
            "name":"商洛市",
            "id":"611000",
            "cityPinyin":"商洛市",
            "lastModifyTime":null,
            "provinceId":"610000",
            "hotCity":false,
            "cityShortPY":"商洛市"
        },
        {
            "name":"兰州市",
            "id":"620100",
            "cityPinyin":"兰州市",
            "lastModifyTime":null,
            "provinceId":"620000",
            "hotCity":false,
            "cityShortPY":"兰州市"
        },
        {
            "name":"嘉峪关市",
            "id":"620200",
            "cityPinyin":"嘉峪关市",
            "lastModifyTime":null,
            "provinceId":"620000",
            "hotCity":false,
            "cityShortPY":"嘉峪关市"
        },
        {
            "name":"金昌市",
            "id":"620300",
            "cityPinyin":"金昌市",
            "lastModifyTime":null,
            "provinceId":"620000",
            "hotCity":false,
            "cityShortPY":"金昌市"
        },
        {
            "name":"白银市",
            "id":"620400",
            "cityPinyin":"白银市",
            "lastModifyTime":null,
            "provinceId":"620000",
            "hotCity":false,
            "cityShortPY":"白银市"
        },
        {
            "name":"天水市",
            "id":"620500",
            "cityPinyin":"天水市",
            "lastModifyTime":null,
            "provinceId":"620000",
            "hotCity":false,
            "cityShortPY":"天水市"
        },
        {
            "name":"武威市",
            "id":"620600",
            "cityPinyin":"武威市",
            "lastModifyTime":null,
            "provinceId":"620000",
            "hotCity":false,
            "cityShortPY":"武威市"
        },
        {
            "name":"张掖市",
            "id":"620700",
            "cityPinyin":"张掖市",
            "lastModifyTime":null,
            "provinceId":"620000",
            "hotCity":false,
            "cityShortPY":"张掖市"
        },
        {
            "name":"平凉市",
            "id":"620800",
            "cityPinyin":"平凉市",
            "lastModifyTime":null,
            "provinceId":"620000",
            "hotCity":false,
            "cityShortPY":"平凉市"
        },
        {
            "name":"酒泉市",
            "id":"620900",
            "cityPinyin":"酒泉市",
            "lastModifyTime":null,
            "provinceId":"620000",
            "hotCity":false,
            "cityShortPY":"酒泉市"
        },
        {
            "name":"庆阳市",
            "id":"621000",
            "cityPinyin":"庆阳市",
            "lastModifyTime":null,
            "provinceId":"620000",
            "hotCity":false,
            "cityShortPY":"庆阳市"
        },
        {
            "name":"定西市",
            "id":"621100",
            "cityPinyin":"定西市",
            "lastModifyTime":null,
            "provinceId":"620000",
            "hotCity":false,
            "cityShortPY":"定西市"
        },
        {
            "name":"陇南市",
            "id":"621200",
            "cityPinyin":"陇南市",
            "lastModifyTime":null,
            "provinceId":"620000",
            "hotCity":false,
            "cityShortPY":"陇南市"
        },
        {
            "name":"临夏回族自治州",
            "id":"622900",
            "cityPinyin":"临夏回族自治州",
            "lastModifyTime":null,
            "provinceId":"620000",
            "hotCity":false,
            "cityShortPY":"临夏回族自治州"
        },
        {
            "name":"甘南藏族自治州",
            "id":"623000",
            "cityPinyin":"甘南藏族自治州",
            "lastModifyTime":null,
            "provinceId":"620000",
            "hotCity":false,
            "cityShortPY":"甘南藏族自治州"
        },
        {
            "name":"西宁市",
            "id":"630100",
            "cityPinyin":"西宁市",
            "lastModifyTime":null,
            "provinceId":"630000",
            "hotCity":false,
            "cityShortPY":"西宁市"
        },
        {
            "name":"海东地区",
            "id":"632100",
            "cityPinyin":"海东地区",
            "lastModifyTime":null,
            "provinceId":"630000",
            "hotCity":false,
            "cityShortPY":"海东地区"
        },
        {
            "name":"海北藏族自治州",
            "id":"632200",
            "cityPinyin":"海北藏族自治州",
            "lastModifyTime":null,
            "provinceId":"630000",
            "hotCity":false,
            "cityShortPY":"海北藏族自治州"
        },
        {
            "name":"黄南藏族自治州",
            "id":"632300",
            "cityPinyin":"黄南藏族自治州",
            "lastModifyTime":null,
            "provinceId":"630000",
            "hotCity":false,
            "cityShortPY":"黄南藏族自治州"
        },
        {
            "name":"海南藏族自治州",
            "id":"632500",
            "cityPinyin":"海南藏族自治州",
            "lastModifyTime":null,
            "provinceId":"630000",
            "hotCity":false,
            "cityShortPY":"海南藏族自治州"
        },
        {
            "name":"果洛藏族自治州",
            "id":"632600",
            "cityPinyin":"果洛藏族自治州",
            "lastModifyTime":null,
            "provinceId":"630000",
            "hotCity":false,
            "cityShortPY":"果洛藏族自治州"
        },
        {
            "name":"玉树藏族自治州",
            "id":"632700",
            "cityPinyin":"玉树藏族自治州",
            "lastModifyTime":null,
            "provinceId":"630000",
            "hotCity":false,
            "cityShortPY":"玉树藏族自治州"
        },
        {
            "name":"海西蒙古族藏族自治州",
            "id":"632800",
            "cityPinyin":"海西蒙古族藏族自治州",
            "lastModifyTime":null,
            "provinceId":"630000",
            "hotCity":false,
            "cityShortPY":"海西蒙古族藏族自治州"
        },
        {
            "name":"银川市",
            "id":"640100",
            "cityPinyin":"银川市",
            "lastModifyTime":null,
            "provinceId":"640000",
            "hotCity":false,
            "cityShortPY":"银川市"
        },
        {
            "name":"石嘴山市",
            "id":"640200",
            "cityPinyin":"石嘴山市",
            "lastModifyTime":null,
            "provinceId":"640000",
            "hotCity":false,
            "cityShortPY":"石嘴山市"
        },
        {
            "name":"吴忠市",
            "id":"640300",
            "cityPinyin":"吴忠市",
            "lastModifyTime":null,
            "provinceId":"640000",
            "hotCity":false,
            "cityShortPY":"吴忠市"
        },
        {
            "name":"固原市",
            "id":"640400",
            "cityPinyin":"固原市",
            "lastModifyTime":null,
            "provinceId":"640000",
            "hotCity":false,
            "cityShortPY":"固原市"
        },
        {
            "name":"中卫市",
            "id":"640500",
            "cityPinyin":"中卫市",
            "lastModifyTime":null,
            "provinceId":"640000",
            "hotCity":false,
            "cityShortPY":"中卫市"
        },
        {
            "name":"乌鲁木齐市",
            "id":"650100",
            "cityPinyin":"乌鲁木齐市",
            "lastModifyTime":null,
            "provinceId":"650000",
            "hotCity":false,
            "cityShortPY":"乌鲁木齐市"
        },
        {
            "name":"克拉玛依市",
            "id":"650200",
            "cityPinyin":"克拉玛依市",
            "lastModifyTime":null,
            "provinceId":"650000",
            "hotCity":false,
            "cityShortPY":"克拉玛依市"
        },
        {
            "name":"吐鲁番地区",
            "id":"652100",
            "cityPinyin":"吐鲁番地区",
            "lastModifyTime":null,
            "provinceId":"650000",
            "hotCity":false,
            "cityShortPY":"吐鲁番地区"
        },
        {
            "name":"哈密地区",
            "id":"652200",
            "cityPinyin":"哈密地区",
            "lastModifyTime":null,
            "provinceId":"650000",
            "hotCity":false,
            "cityShortPY":"哈密地区"
        },
        {
            "name":"昌吉回族自治州",
            "id":"652300",
            "cityPinyin":"昌吉回族自治州",
            "lastModifyTime":null,
            "provinceId":"650000",
            "hotCity":false,
            "cityShortPY":"昌吉回族自治州"
        },
        {
            "name":"博尔塔拉蒙古自治州",
            "id":"652700",
            "cityPinyin":"博尔塔拉蒙古自治州",
            "lastModifyTime":null,
            "provinceId":"650000",
            "hotCity":false,
            "cityShortPY":"博尔塔拉蒙古自治州"
        },
        {
            "name":"巴音郭楞蒙古自治州",
            "id":"652800",
            "cityPinyin":"巴音郭楞蒙古自治州",
            "lastModifyTime":null,
            "provinceId":"650000",
            "hotCity":false,
            "cityShortPY":"巴音郭楞蒙古自治州"
        },
        {
            "name":"阿克苏地区",
            "id":"652900",
            "cityPinyin":"阿克苏地区",
            "lastModifyTime":null,
            "provinceId":"650000",
            "hotCity":false,
            "cityShortPY":"阿克苏地区"
        },
        {
            "name":"克孜勒苏柯尔克孜自治州",
            "id":"653000",
            "cityPinyin":"克孜勒苏柯尔克孜自治州",
            "lastModifyTime":null,
            "provinceId":"650000",
            "hotCity":false,
            "cityShortPY":"克孜勒苏柯尔克孜自治州"
        },
        {
            "name":"喀什地区",
            "id":"653100",
            "cityPinyin":"喀什地区",
            "lastModifyTime":null,
            "provinceId":"650000",
            "hotCity":false,
            "cityShortPY":"喀什地区"
        },
        {
            "name":"和田地区",
            "id":"653200",
            "cityPinyin":"和田地区",
            "lastModifyTime":null,
            "provinceId":"650000",
            "hotCity":false,
            "cityShortPY":"和田地区"
        },
        {
            "name":"伊犁哈萨克自治州",
            "id":"654000",
            "cityPinyin":"伊犁哈萨克自治州",
            "lastModifyTime":null,
            "provinceId":"650000",
            "hotCity":false,
            "cityShortPY":"伊犁哈萨克自治州"
        },
        {
            "name":"塔城地区",
            "id":"654200",
            "cityPinyin":"塔城地区",
            "lastModifyTime":null,
            "provinceId":"650000",
            "hotCity":false,
            "cityShortPY":"塔城地区"
        },
        {
            "name":"阿勒泰地区",
            "id":"654300",
            "cityPinyin":"阿勒泰地区",
            "lastModifyTime":null,
            "provinceId":"650000",
            "hotCity":false,
            "cityShortPY":"阿勒泰地区"
        },
        {
            "name":"省直辖行政单位",
            "id":"659000",
            "cityPinyin":"省直辖行政单位",
            "lastModifyTime":null,
            "provinceId":"650000",
            "hotCity":false,
            "cityShortPY":"省直辖行政单位"
        }
    ]
}