<link rel="stylesheet" type="text/css" href="${CONTEXT}css/global.css"/>
<script type="text/javascript" src="${CONTEXT}js/jquery.min.js"></script>
<script type="text/javascript" src="${CONTEXT}js/common.js"></script>
<script type="text/javascript" src="${CONTEXT}js/jquery.validatebox.fixed.js"></script>
<script type="text/javascript" src="${CONTEXT}js/jquery.validate.js"></script>
<script type="text/javascript" src="${CONTEXT}js/jquery.ajaxfileupload.js"></script>
<script type="text/javascript">
var CONTEXT = "${CONTEXT}";
</script>
